apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dbserver-deployment
  labels:
    app: dbserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbserver
  template:
    metadata:
      labels:
        app: dbserver
    spec:
      containers:
      - name: dbserver
        image: postgres
        resources:
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: dbserver-config
              key: password
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: dbserver-config
              key: username
        volumeMounts:
        - name: persistent-storage
          mountPath: /var/lib/postgresql/data         
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
            claimName: postgres-claim

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: dbserver-service
  labels:
    app: dbserver
spec:
  type: NodePort  
  ports:
  - port: 5432
    targetPort: 5432 
  selector:
    app: dbserver
